// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

ApiNamesWalletStatus configureNamesV1({
  required String dbPath,
  required String network,
  required BigInt runtimeActivationHeight,
  required BigInt namesActivationHeight,
  required BigInt epochSize,
  required BigInt commitTtlBlocks,
  required BigInt refreshDeadlineBlocks,
  required BigInt leaseDurationBlocks,
  required BigInt gracePeriodBlocks,
  required BigInt reuseDelayBlocks,
  required BigInt maxRecordBytes,
  required BigInt minimumBondZatoshis,
  required BigInt retentionBlocks,
  required String networkDomain,
  required String rendezvousIvkHex,
  required String rendezvousReceiverHex,
}) => RustLib.instance.api.crateApiNamesConfigureNamesV1(
  dbPath: dbPath,
  network: network,
  runtimeActivationHeight: runtimeActivationHeight,
  namesActivationHeight: namesActivationHeight,
  epochSize: epochSize,
  commitTtlBlocks: commitTtlBlocks,
  refreshDeadlineBlocks: refreshDeadlineBlocks,
  leaseDurationBlocks: leaseDurationBlocks,
  gracePeriodBlocks: gracePeriodBlocks,
  reuseDelayBlocks: reuseDelayBlocks,
  maxRecordBytes: maxRecordBytes,
  minimumBondZatoshis: minimumBondZatoshis,
  retentionBlocks: retentionBlocks,
  networkDomain: networkDomain,
  rendezvousIvkHex: rendezvousIvkHex,
  rendezvousReceiverHex: rendezvousReceiverHex,
);

ApiNamesWalletStatus getNamesV1Status({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiNamesGetNamesV1Status(
  dbPath: dbPath,
  network: network,
);

Future<ApiNamesWalletStatus> bootstrapNamesV1({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
}) => RustLib.instance.api.crateApiNamesBootstrapNamesV1(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
);

Future<ApiNamesResolution> resolveNameV1({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String name,
}) => RustLib.instance.api.crateApiNamesResolveNameV1(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  name: name,
);

class ApiNamesResolution {
  final String status;
  final Uint8List? record;
  final String? paymentAddress;
  final BigInt? sequence;
  final BigInt? leaseExpiry;
  final BigInt? terminalHeight;
  final Uint8List? stateCommitment;
  final BigInt tipHeight;
  final BigInt candidateBlockProbes;
  final BigInt tailBlocksScanned;
  final BigInt lineageBlockProbes;
  final BigInt predecessorChainSteps;

  const ApiNamesResolution({
    required this.status,
    this.record,
    this.paymentAddress,
    this.sequence,
    this.leaseExpiry,
    this.terminalHeight,
    this.stateCommitment,
    required this.tipHeight,
    required this.candidateBlockProbes,
    required this.tailBlocksScanned,
    required this.lineageBlockProbes,
    required this.predecessorChainSteps,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      record.hashCode ^
      paymentAddress.hashCode ^
      sequence.hashCode ^
      leaseExpiry.hashCode ^
      terminalHeight.hashCode ^
      stateCommitment.hashCode ^
      tipHeight.hashCode ^
      candidateBlockProbes.hashCode ^
      tailBlocksScanned.hashCode ^
      lineageBlockProbes.hashCode ^
      predecessorChainSteps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesResolution &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          record == other.record &&
          paymentAddress == other.paymentAddress &&
          sequence == other.sequence &&
          leaseExpiry == other.leaseExpiry &&
          terminalHeight == other.terminalHeight &&
          stateCommitment == other.stateCommitment &&
          tipHeight == other.tipHeight &&
          candidateBlockProbes == other.candidateBlockProbes &&
          tailBlocksScanned == other.tailBlocksScanned &&
          lineageBlockProbes == other.lineageBlockProbes &&
          predecessorChainSteps == other.predecessorChainSteps;
}

class ApiNamesWalletStatus {
  final String state;
  final String message;
  final bool configured;
  final BigInt tipHeight;
  final BigInt namesActivationHeight;
  final BigInt oldestRewindHeight;

  const ApiNamesWalletStatus({
    required this.state,
    required this.message,
    required this.configured,
    required this.tipHeight,
    required this.namesActivationHeight,
    required this.oldestRewindHeight,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      configured.hashCode ^
      tipHeight.hashCode ^
      namesActivationHeight.hashCode ^
      oldestRewindHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesWalletStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          configured == other.configured &&
          tipHeight == other.tipHeight &&
          namesActivationHeight == other.namesActivationHeight &&
          oldestRewindHeight == other.oldestRewindHeight;
}
