// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

ApiNamesWalletStatus configureNamesV1({
  required String dbPath,
  required String network,
  required BigInt runtimeActivationHeight,
  required BigInt namesActivationHeight,
  required BigInt epochSize,
  required BigInt commitTtlBlocks,
  required BigInt refreshDeadlineBlocks,
  required BigInt leaseDurationBlocks,
  required BigInt gracePeriodBlocks,
  required BigInt reuseDelayBlocks,
  required BigInt maxRecordBytes,
  required BigInt minimumBondZatoshis,
  required BigInt retentionBlocks,
  required String networkDomain,
  required String rendezvousIvkHex,
  required String rendezvousReceiverHex,
}) => RustLib.instance.api.crateApiNamesConfigureNamesV1(
  dbPath: dbPath,
  network: network,
  runtimeActivationHeight: runtimeActivationHeight,
  namesActivationHeight: namesActivationHeight,
  epochSize: epochSize,
  commitTtlBlocks: commitTtlBlocks,
  refreshDeadlineBlocks: refreshDeadlineBlocks,
  leaseDurationBlocks: leaseDurationBlocks,
  gracePeriodBlocks: gracePeriodBlocks,
  reuseDelayBlocks: reuseDelayBlocks,
  maxRecordBytes: maxRecordBytes,
  minimumBondZatoshis: minimumBondZatoshis,
  retentionBlocks: retentionBlocks,
  networkDomain: networkDomain,
  rendezvousIvkHex: rendezvousIvkHex,
  rendezvousReceiverHex: rendezvousReceiverHex,
);

ApiNamesWalletStatus getNamesV1Status({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiNamesGetNamesV1Status(
  dbPath: dbPath,
  network: network,
);

/// Checks the selected account for an exact, spendable and unreserved one-ZEC
/// Ironwood note. A `needs_preparation` result tells the UI to ask the wallet
/// send engine for an ordinary one-ZEC self-transfer before COMMIT.
ApiNamesBondStatus getNamesV1BondStatus({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiNamesGetNamesV1BondStatus(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

List<ApiManagedName> getManagedNamesV1({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiNamesGetManagedNamesV1(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Persist a registration intent before the wallet prepares an exact bond.
/// If an eligible note already exists it is immediately reserved; otherwise
/// sync will reserve the self-transfer output as soon as it is confirmed.
Future<ApiNamesRegistrationDraft> prepareNamesV1RegistrationDraft({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String name,
  required String paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesPrepareNamesV1RegistrationDraft(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  name: name,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

/// Discards an uncompleted wallet-local workflow after the user explicitly
/// abandons it. Canonical COMMIT/REVEAL state is never altered here.
void discardNamesV1RegistrationWorkflow({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String name,
}) => RustLib.instance.api.crateApiNamesDiscardNamesV1RegistrationWorkflow(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  name: name,
);

/// Reserve the exact one-ZEC registration bond and create a COMMIT carrier
/// proposal. This intentionally does not broadcast: the established wallet
/// review and credential flow remains the sole transaction-execution path.
Future<ApiNamesCommitProposal> beginNamesV1Registration({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String name,
  required String paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesBeginNamesV1Registration(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  name: name,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

/// Builds and signs a Names REVEAL for the exact scheduled anchor, but does
/// not broadcast. Execution is later routed through the ordinary proposal
/// review/confirmation entrypoint.
Future<ApiNamesRevealProposal> beginNamesV1Reveal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String name,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesBeginNamesV1Reveal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  name: name,
  mnemonicBytes: mnemonicBytes,
);

/// Proves and broadcasts REVEAL after the runtime has authenticated the exact
/// accepted COMMIT and the canonical schedule reaches this name's anchor.
Future<Uint8List> revealNamesV1Registration({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String name,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesRevealNamesV1Registration(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  name: name,
  mnemonicBytes: mnemonicBytes,
);

/// Proves and broadcasts one canonical current-head transition.
Future<Uint8List> manageNameV1({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String name,
  required String action,
  String? paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesManageNameV1(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  name: name,
  action: action,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

Future<ApiNamesWalletStatus> bootstrapNamesV1({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
}) => RustLib.instance.api.crateApiNamesBootstrapNamesV1(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
);

Future<ApiNamesResolution> resolveNameV1({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String name,
}) => RustLib.instance.api.crateApiNamesResolveNameV1(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  name: name,
);

class ApiManagedName {
  final String name;
  final String? paymentAddress;
  final String phase;
  final Uint8List commitment;

  /// Present only after canonical replay has authenticated this exact
  /// COMMIT. These are workflow display values, not independent evidence.
  final BigInt? commitHeight;
  final BigInt? commitExpiryHeight;
  final BigInt? commitBlocksRemaining;
  final BigInt? nextRevealHeight;
  final BigInt? revealBlocksUntil;
  final bool revealReady;

  const ApiManagedName({
    required this.name,
    this.paymentAddress,
    required this.phase,
    required this.commitment,
    this.commitHeight,
    this.commitExpiryHeight,
    this.commitBlocksRemaining,
    this.nextRevealHeight,
    this.revealBlocksUntil,
    required this.revealReady,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      paymentAddress.hashCode ^
      phase.hashCode ^
      commitment.hashCode ^
      commitHeight.hashCode ^
      commitExpiryHeight.hashCode ^
      commitBlocksRemaining.hashCode ^
      nextRevealHeight.hashCode ^
      revealBlocksUntil.hashCode ^
      revealReady.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiManagedName &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          paymentAddress == other.paymentAddress &&
          phase == other.phase &&
          commitment == other.commitment &&
          commitHeight == other.commitHeight &&
          commitExpiryHeight == other.commitExpiryHeight &&
          commitBlocksRemaining == other.commitBlocksRemaining &&
          nextRevealHeight == other.nextRevealHeight &&
          revealBlocksUntil == other.revealBlocksUntil &&
          revealReady == other.revealReady;
}

/// Wallet-owned denomination readiness for starting a registration.
class ApiNamesBondStatus {
  final String state;
  final BigInt requiredZatoshi;
  final int exactNoteCount;
  final BigInt spendableIronwoodZatoshi;

  const ApiNamesBondStatus({
    required this.state,
    required this.requiredZatoshi,
    required this.exactNoteCount,
    required this.spendableIronwoodZatoshi,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      requiredZatoshi.hashCode ^
      exactNoteCount.hashCode ^
      spendableIronwoodZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesBondStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          requiredZatoshi == other.requiredZatoshi &&
          exactNoteCount == other.exactNoteCount &&
          spendableIronwoodZatoshi == other.spendableIronwoodZatoshi;
}

/// Ordinary-wallet proposal that carries a Names COMMIT. The caller sends it
/// through the same review/prove/broadcast path as every other wallet send.
class ApiNamesCommitProposal {
  final BigInt proposalId;
  final BigInt feeZatoshi;
  final Uint8List commitment;

  const ApiNamesCommitProposal({
    required this.proposalId,
    required this.feeZatoshi,
    required this.commitment,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^ feeZatoshi.hashCode ^ commitment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesCommitProposal &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          feeZatoshi == other.feeZatoshi &&
          commitment == other.commitment;
}

/// Durable registration intent state. A draft survives the ordinary wallet
/// self-transfer used to form an exact bond denomination.
class ApiNamesRegistrationDraft {
  final String phase;

  const ApiNamesRegistrationDraft({required this.phase});

  @override
  int get hashCode => phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesRegistrationDraft &&
          runtimeType == other.runtimeType &&
          phase == other.phase;
}

class ApiNamesResolution {
  final String status;
  final Uint8List? record;
  final String? paymentAddress;
  final BigInt? sequence;
  final BigInt? leaseExpiry;
  final BigInt? terminalHeight;
  final Uint8List? stateCommitment;
  final BigInt tipHeight;
  final BigInt candidateBlockProbes;
  final BigInt tailBlocksScanned;
  final BigInt lineageBlockProbes;
  final BigInt predecessorChainSteps;

  const ApiNamesResolution({
    required this.status,
    this.record,
    this.paymentAddress,
    this.sequence,
    this.leaseExpiry,
    this.terminalHeight,
    this.stateCommitment,
    required this.tipHeight,
    required this.candidateBlockProbes,
    required this.tailBlocksScanned,
    required this.lineageBlockProbes,
    required this.predecessorChainSteps,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      record.hashCode ^
      paymentAddress.hashCode ^
      sequence.hashCode ^
      leaseExpiry.hashCode ^
      terminalHeight.hashCode ^
      stateCommitment.hashCode ^
      tipHeight.hashCode ^
      candidateBlockProbes.hashCode ^
      tailBlocksScanned.hashCode ^
      lineageBlockProbes.hashCode ^
      predecessorChainSteps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesResolution &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          record == other.record &&
          paymentAddress == other.paymentAddress &&
          sequence == other.sequence &&
          leaseExpiry == other.leaseExpiry &&
          terminalHeight == other.terminalHeight &&
          stateCommitment == other.stateCommitment &&
          tipHeight == other.tipHeight &&
          candidateBlockProbes == other.candidateBlockProbes &&
          tailBlocksScanned == other.tailBlocksScanned &&
          lineageBlockProbes == other.lineageBlockProbes &&
          predecessorChainSteps == other.predecessorChainSteps;
}

/// Reviewed REVEAL proposal backed by an atomically consumed Rust capability.
class ApiNamesRevealProposal {
  final BigInt proposalId;
  final BigInt feeZatoshi;

  const ApiNamesRevealProposal({
    required this.proposalId,
    required this.feeZatoshi,
  });

  @override
  int get hashCode => proposalId.hashCode ^ feeZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesRevealProposal &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          feeZatoshi == other.feeZatoshi;
}

class ApiNamesWalletStatus {
  final String state;
  final String message;
  final bool configured;
  final BigInt tipHeight;
  final BigInt namesActivationHeight;
  final BigInt oldestRewindHeight;

  const ApiNamesWalletStatus({
    required this.state,
    required this.message,
    required this.configured,
    required this.tipHeight,
    required this.namesActivationHeight,
    required this.oldestRewindHeight,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      configured.hashCode ^
      tipHeight.hashCode ^
      namesActivationHeight.hashCode ^
      oldestRewindHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesWalletStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          configured == other.configured &&
          tipHeight == other.tipHeight &&
          namesActivationHeight == other.namesActivationHeight &&
          oldestRewindHeight == other.oldestRewindHeight;
}
