// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

ApiNamesWalletStatus configureNames({
  required String dbPath,
  required String network,
  required BigInt retentionBlocks,
}) => RustLib.instance.api.crateApiNamesConfigureNames(
  dbPath: dbPath,
  network: network,
  retentionBlocks: retentionBlocks,
);

ApiNamesWalletStatus getNamesStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiNamesGetNamesStatus(
  dbPath: dbPath,
  network: network,
);

/// Checks the selected account for an exact, spendable and unreserved one-ZEC
/// Ironwood note. A `needs_preparation` result tells the UI to ask the wallet
/// send engine for an ordinary one-ZEC self-transfer before COMMIT.
ApiNamesBondStatus getNamesBondStatus({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiNamesGetNamesBondStatus(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

List<ApiManagedName> getManagedNames({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiNamesGetManagedNames(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Explicitly recovers one already-owned name into `Your names`. This is
/// intentionally separate from ordinary resolution: it authenticates the
/// exact current head, verifies seed-derived ownership, and retains the
/// existing bond witness without broadcasting a transaction.
Future<void> recoverNamesRegistration({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String name,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesRecoverNamesRegistration(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  name: name,
  mnemonicBytes: mnemonicBytes,
);

/// Persist a registration intent before the wallet prepares an exact bond.
/// If an eligible note already exists it is immediately reserved; otherwise
/// sync will reserve the self-transfer output as soon as it is confirmed.
Future<ApiNamesRegistrationDraft> prepareNamesRegistrationDraft({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String name,
  required String paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesPrepareNamesRegistrationDraft(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  name: name,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

/// Discards an uncompleted wallet-local workflow after the user explicitly
/// abandons it. Canonical COMMIT/REVEAL state is never altered here.
void discardNamesRegistrationWorkflow({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String name,
}) => RustLib.instance.api.crateApiNamesDiscardNamesRegistrationWorkflow(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  name: name,
);

/// Reserve the exact one-ZEC registration bond and create a COMMIT carrier
/// proposal. This intentionally does not broadcast: the established wallet
/// review and credential flow remains the sole transaction-execution path.
Future<ApiNamesCommitProposal> beginNamesRegistration({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String name,
  required String paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesBeginNamesRegistration(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  name: name,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

/// Builds and signs a Names REVEAL after the canonical COMMIT is accepted and
/// while its protocol-defined TTL is still live. Execution is later routed
/// through the ordinary proposal review/confirmation entrypoint.
Future<ApiNamesRevealProposal> beginNamesReveal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String name,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesBeginNamesReveal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  name: name,
  mnemonicBytes: mnemonicBytes,
);

/// Proves and broadcasts REVEAL after the runtime has authenticated the exact
/// accepted COMMIT and the protocol-defined COMMIT TTL is still live.
Future<Uint8List> revealNamesRegistration({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String name,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesRevealNamesRegistration(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  name: name,
  mnemonicBytes: mnemonicBytes,
);

/// Builds a current-head Names transition for the shared wallet review flow.
/// Construction reserves any fee input, but nothing is broadcast here.
Future<ApiNamesRevealProposal> beginNamesManagement({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String name,
  required String action,
  String? paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesBeginNamesManagement(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  name: name,
  action: action,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

/// Proves and broadcasts one canonical current-head transition.
/// Retained for non-UI qualification callers; wallet UI must use
/// `begin_names_management` and the shared review flow.
Future<Uint8List> manageName({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String name,
  required String action,
  String? paymentAddress,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiNamesManageName(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  name: name,
  action: action,
  paymentAddress: paymentAddress,
  mnemonicBytes: mnemonicBytes,
);

Future<ApiNamesWalletStatus> bootstrapNames({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
}) => RustLib.instance.api.crateApiNamesBootstrapNames(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
);

Future<ApiNamesResolution> resolveName({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String name,
}) => RustLib.instance.api.crateApiNamesResolveName(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  name: name,
);

class ApiManagedName {
  final String name;
  final String? paymentAddress;
  final String phase;
  final Uint8List commitment;

  /// Present only after canonical replay has authenticated this exact
  /// COMMIT. These are workflow display values, not independent evidence.
  final BigInt? commitHeight;
  final BigInt? commitExpiryHeight;
  final BigInt? commitBlocksRemaining;

  /// Half-open inclusion-height window in which this draft's COMMIT can
  /// mature for its already-bound REVEAL height without expiring.
  final BigInt commitWindowStart;
  final BigInt commitWindowEnd;
  final BigInt commitBlocksUntil;
  final bool commitWindowOpen;

  /// The deterministic half-open REVEAL window selected by this workflow.
  final BigInt revealWindowStart;
  final BigInt revealWindowEnd;
  final BigInt revealBlocksUntil;
  final bool revealWindowOpen;

  /// Next deterministic REFRESH window for an active accepted head.
  final BigInt? refreshWindowStart;
  final BigInt? refreshWindowEnd;
  final BigInt? refreshBlocksUntil;
  final bool refreshWindowOpen;

  const ApiManagedName({
    required this.name,
    this.paymentAddress,
    required this.phase,
    required this.commitment,
    this.commitHeight,
    this.commitExpiryHeight,
    this.commitBlocksRemaining,
    required this.commitWindowStart,
    required this.commitWindowEnd,
    required this.commitBlocksUntil,
    required this.commitWindowOpen,
    required this.revealWindowStart,
    required this.revealWindowEnd,
    required this.revealBlocksUntil,
    required this.revealWindowOpen,
    this.refreshWindowStart,
    this.refreshWindowEnd,
    this.refreshBlocksUntil,
    required this.refreshWindowOpen,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      paymentAddress.hashCode ^
      phase.hashCode ^
      commitment.hashCode ^
      commitHeight.hashCode ^
      commitExpiryHeight.hashCode ^
      commitBlocksRemaining.hashCode ^
      commitWindowStart.hashCode ^
      commitWindowEnd.hashCode ^
      commitBlocksUntil.hashCode ^
      commitWindowOpen.hashCode ^
      revealWindowStart.hashCode ^
      revealWindowEnd.hashCode ^
      revealBlocksUntil.hashCode ^
      revealWindowOpen.hashCode ^
      refreshWindowStart.hashCode ^
      refreshWindowEnd.hashCode ^
      refreshBlocksUntil.hashCode ^
      refreshWindowOpen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiManagedName &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          paymentAddress == other.paymentAddress &&
          phase == other.phase &&
          commitment == other.commitment &&
          commitHeight == other.commitHeight &&
          commitExpiryHeight == other.commitExpiryHeight &&
          commitBlocksRemaining == other.commitBlocksRemaining &&
          commitWindowStart == other.commitWindowStart &&
          commitWindowEnd == other.commitWindowEnd &&
          commitBlocksUntil == other.commitBlocksUntil &&
          commitWindowOpen == other.commitWindowOpen &&
          revealWindowStart == other.revealWindowStart &&
          revealWindowEnd == other.revealWindowEnd &&
          revealBlocksUntil == other.revealBlocksUntil &&
          revealWindowOpen == other.revealWindowOpen &&
          refreshWindowStart == other.refreshWindowStart &&
          refreshWindowEnd == other.refreshWindowEnd &&
          refreshBlocksUntil == other.refreshBlocksUntil &&
          refreshWindowOpen == other.refreshWindowOpen;
}

/// Wallet-owned denomination readiness for starting a registration.
class ApiNamesBondStatus {
  final String state;
  final BigInt requiredZatoshi;
  final int exactNoteCount;
  final BigInt spendableIronwoodZatoshi;

  const ApiNamesBondStatus({
    required this.state,
    required this.requiredZatoshi,
    required this.exactNoteCount,
    required this.spendableIronwoodZatoshi,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      requiredZatoshi.hashCode ^
      exactNoteCount.hashCode ^
      spendableIronwoodZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesBondStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          requiredZatoshi == other.requiredZatoshi &&
          exactNoteCount == other.exactNoteCount &&
          spendableIronwoodZatoshi == other.spendableIronwoodZatoshi;
}

/// Ordinary-wallet proposal that carries a Names COMMIT. The caller sends it
/// through the same review/prove/broadcast path as every other wallet send.
class ApiNamesCommitProposal {
  final BigInt proposalId;
  final BigInt feeZatoshi;
  final Uint8List commitment;

  const ApiNamesCommitProposal({
    required this.proposalId,
    required this.feeZatoshi,
    required this.commitment,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^ feeZatoshi.hashCode ^ commitment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesCommitProposal &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          feeZatoshi == other.feeZatoshi &&
          commitment == other.commitment;
}

/// Durable registration intent state. A draft survives the ordinary wallet
/// self-transfer used to form an exact bond denomination.
class ApiNamesRegistrationDraft {
  final String phase;

  const ApiNamesRegistrationDraft({required this.phase});

  @override
  int get hashCode => phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesRegistrationDraft &&
          runtimeType == other.runtimeType &&
          phase == other.phase;
}

class ApiNamesResolution {
  final String status;
  final String? paymentAddress;
  final BigInt? leaseExpiry;
  final BigInt? terminalHeight;
  final Uint8List? producerTxid;
  final BigInt? producerHeight;
  final BigInt? producerTxIndex;
  final BigInt? producerActionIndex;
  final BigInt tipHeight;
  final BigInt compactBlocksScanned;

  const ApiNamesResolution({
    required this.status,
    this.paymentAddress,
    this.leaseExpiry,
    this.terminalHeight,
    this.producerTxid,
    this.producerHeight,
    this.producerTxIndex,
    this.producerActionIndex,
    required this.tipHeight,
    required this.compactBlocksScanned,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      paymentAddress.hashCode ^
      leaseExpiry.hashCode ^
      terminalHeight.hashCode ^
      producerTxid.hashCode ^
      producerHeight.hashCode ^
      producerTxIndex.hashCode ^
      producerActionIndex.hashCode ^
      tipHeight.hashCode ^
      compactBlocksScanned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesResolution &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          paymentAddress == other.paymentAddress &&
          leaseExpiry == other.leaseExpiry &&
          terminalHeight == other.terminalHeight &&
          producerTxid == other.producerTxid &&
          producerHeight == other.producerHeight &&
          producerTxIndex == other.producerTxIndex &&
          producerActionIndex == other.producerActionIndex &&
          tipHeight == other.tipHeight &&
          compactBlocksScanned == other.compactBlocksScanned;
}

/// Reviewed Names proposal backed by an atomically consumed Rust capability.
class ApiNamesRevealProposal {
  final BigInt proposalId;
  final BigInt feeZatoshi;

  const ApiNamesRevealProposal({
    required this.proposalId,
    required this.feeZatoshi,
  });

  @override
  int get hashCode => proposalId.hashCode ^ feeZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesRevealProposal &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          feeZatoshi == other.feeZatoshi;
}

class ApiNamesWalletStatus {
  final String state;
  final String message;
  final bool configured;
  final BigInt tipHeight;
  final BigInt namesActivationHeight;
  final BigInt oldestRewindHeight;

  const ApiNamesWalletStatus({
    required this.state,
    required this.message,
    required this.configured,
    required this.tipHeight,
    required this.namesActivationHeight,
    required this.oldestRewindHeight,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      configured.hashCode ^
      tipHeight.hashCode ^
      namesActivationHeight.hashCode ^
      oldestRewindHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiNamesWalletStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          configured == other.configured &&
          tipHeight == other.tipHeight &&
          namesActivationHeight == other.namesActivationHeight &&
          oldestRewindHeight == other.oldestRewindHeight;
}
