// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network_privacy.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_headers`, `binary_search_birthday_height`, `block_at_height`, `collect_body`, `correct_estimated_height`, `divide_round_nearest`, `estimate_mainnet_birthday_height`, `interpolate_height`, `is_mainnet`, `mainnet_anchor_segment`, `network_http_response`, `timed_birthday_request`, `with_api_response_body_timeout`, `with_tor_http_request_cancellation`, `with_tor_http_request_timeout`, `write_body_to_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BirthdayAnchor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Blocks new policy-aware direct requests immediately. Tor bootstrap is
/// intentionally separate so the caller can first quiesce channels that were
/// opened while direct mode was active.
void beginNetworkPrivacyEnable() =>
    RustLib.instance.api.crateApiNetworkPrivacyBeginNetworkPrivacyEnable();

/// Waits until direct tonic connections cancelled by
/// [begin_network_privacy_enable] have released their sockets.
Future<void> quiesceNetworkPrivacyDirectRequests() => RustLib.instance.api
    .crateApiNetworkPrivacyQuiesceNetworkPrivacyDirectRequests();

/// Configures the process-wide network route used by wallet gRPC and HTTP
/// clients. Enabling is fail-closed: the desired route changes before Tor
/// bootstrapping starts, so a bootstrap failure cannot fall back to clearnet.
Future<NetworkPrivacyStatus> configureNetworkPrivacy({
  required bool enabled,
  required String torDirectory,
}) => RustLib.instance.api.crateApiNetworkPrivacyConfigureNetworkPrivacy(
  enabled: enabled,
  torDirectory: torDirectory,
);

/// Returns the current runtime state. `Bootstrapping` and `Failed` both mean
/// that app network requests are blocked while Tor remains the desired route.
NetworkPrivacyStatus getNetworkPrivacyStatus() =>
    RustLib.instance.api.crateApiNetworkPrivacyGetNetworkPrivacyStatus();

bool isTorEnabled() =>
    RustLib.instance.api.crateApiNetworkPrivacyIsTorEnabled();

/// Suspends or resumes Tor's circuit maintenance alongside the app lifecycle.
///
/// A bootstrapped client otherwise keeps guard connections and directory tasks
/// running while the app is in the background, which costs battery on mobile
/// and does work iOS will kill the app for. A no-op until Tor is connected.
void setNetworkPrivacyDormant({required bool dormant}) => RustLib.instance.api
    .crateApiNetworkPrivacySetNetworkPrivacyDormant(dormant: dormant);

/// Starts a token-protected loopback server that streams HTTPS update assets
/// from the embedded Tor client directly to a native desktop updater.
Future<String> startTorUpdateRelay() =>
    RustLib.instance.api.crateApiNetworkPrivacyStartTorUpdateRelay();

/// Stops the loopback update relay and cancels any active package transfer.
Future<void> stopTorUpdateRelay() =>
    RustLib.instance.api.crateApiNetworkPrivacyStopTorUpdateRelay();

/// Makes a GET request on a fresh Tor circuit. Dart calls this only after its
/// process-wide route check has selected Tor; direct requests stay in Dart so
/// existing test injection and platform behaviour remain unchanged.
Future<NetworkHttpResponse> torHttpGet({
  required String url,
  required List<NetworkHttpHeader> headers,
  BigInt? timeoutMilliseconds,
  BigInt? requestId,
}) => RustLib.instance.api.crateApiNetworkPrivacyTorHttpGet(
  url: url,
  headers: headers,
  timeoutMilliseconds: timeoutMilliseconds,
  requestId: requestId,
);

/// Makes a POST request on a fresh Tor circuit. Every app-owned HTTP call is
/// isolated from wallet gRPC and from other HTTP destinations.
Future<NetworkHttpResponse> torHttpPost({
  required String url,
  required List<NetworkHttpHeader> headers,
  required List<int> body,
  BigInt? timeoutMilliseconds,
  BigInt? requestId,
}) => RustLib.instance.api.crateApiNetworkPrivacyTorHttpPost(
  url: url,
  headers: headers,
  body: body,
  timeoutMilliseconds: timeoutMilliseconds,
  requestId: requestId,
);

/// Reserves a process-unique cancellation token for one Tor HTTP request.
BigInt torHttpBeginRequest() =>
    RustLib.instance.api.crateApiNetworkPrivacyTorHttpBeginRequest();

/// Cancels one in-flight Tor HTTP request without affecting other circuits.
void torHttpCancelRequest({required BigInt requestId}) => RustLib.instance.api
    .crateApiNetworkPrivacyTorHttpCancelRequest(requestId: requestId);

/// Streams an HTTP GET response over an isolated Tor route directly to disk.
/// This avoids moving large proving-parameter files through Rust and Dart
/// whole-body buffers.
Future<NetworkHttpResponse> torHttpDownload({
  required String url,
  required List<NetworkHttpHeader> headers,
  required String destinationPath,
}) => RustLib.instance.api.crateApiNetworkPrivacyTorHttpDownload(
  url: url,
  headers: headers,
  destinationPath: destinationPath,
);

Future<ImportBirthdayMetadata> getImportBirthdayMetadata({
  required String lightwalletdUrl,
  required bool useMainnetFastPath,
}) => RustLib.instance.api.crateApiNetworkPrivacyGetImportBirthdayMetadata(
  lightwalletdUrl: lightwalletdUrl,
  useMainnetFastPath: useMainnetFastPath,
);

Future<BigInt> estimateImportBirthdayHeight({
  required String lightwalletdUrl,
  required PlatformInt64 targetEpochSeconds,
  required bool useMainnetFastPath,
  BigInt? tipHeight,
  int? tipTime,
}) => RustLib.instance.api.crateApiNetworkPrivacyEstimateImportBirthdayHeight(
  lightwalletdUrl: lightwalletdUrl,
  targetEpochSeconds: targetEpochSeconds,
  useMainnetFastPath: useMainnetFastPath,
  tipHeight: tipHeight,
  tipTime: tipTime,
);

class ImportBirthdayMetadata {
  final BigInt saplingActivationHeight;
  final int saplingActivationTime;
  final BigInt tipHeight;
  final int tipTime;

  const ImportBirthdayMetadata({
    required this.saplingActivationHeight,
    required this.saplingActivationTime,
    required this.tipHeight,
    required this.tipTime,
  });

  @override
  int get hashCode =>
      saplingActivationHeight.hashCode ^
      saplingActivationTime.hashCode ^
      tipHeight.hashCode ^
      tipTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportBirthdayMetadata &&
          runtimeType == other.runtimeType &&
          saplingActivationHeight == other.saplingActivationHeight &&
          saplingActivationTime == other.saplingActivationTime &&
          tipHeight == other.tipHeight &&
          tipTime == other.tipTime;
}

class NetworkHttpHeader {
  final String name;
  final String value;

  const NetworkHttpHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkHttpHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class NetworkHttpResponse {
  final int statusCode;
  final List<NetworkHttpHeader> headers;
  final Uint8List body;

  const NetworkHttpResponse({
    required this.statusCode,
    required this.headers,
    required this.body,
  });

  @override
  int get hashCode => statusCode.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkHttpResponse &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          headers == other.headers &&
          body == other.body;
}
